// Создание пользователя, Регистрация
POST https://boring-weekend.uyem.ru/api/v1/user/create HTTP/1.1
content-type: application/json

// параметры
{
  "args": {
    "data": {
      "email": "19_pek@mail.ru",
      "password": "123456"
    }
  },
  "passwordRepeat": "123456"
}