// получение нескольких пользователей
POST https://boring-weekend.uyem.ru/api/v1/user/findmany HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTksInBhc3N3b3JkIjoiJDJiJDEwJEJXcURhYXBXakdKeTc4TEtWRnpmLnV2MUg5c2p1UE92ZHhMdnRPWUZ4dUxaa05HZHprYnRxIiwiaWF0IjoxNjM0MTg5NjkyfQ.lbUfSI0L3YIZFLCxQxTE3S8BOF1QxRrMHl58ovTCxRk



// параметры
{
  "where": {
    "id": 11,
  },
  "skip": 1,
  "take": 2,
}